### ISSUE TITLE
ERROR: No matching distribution found for soft_renderer.

### ISSUE THREAD

**Issue by shichaog** [JustusThies/NeuralVoicePuppetry#10]
Very cool project! I would love to try to get a local version of it running.

(NeuralVoicePuppetry-venv) ➜  ~ pip install soft_renderer
ERROR: Could not find a version that satisfies the requirement soft_renderer (from versions: none)
ERROR: No matching distribution found for soft_renderer

I want to train model. when install soft_renderer it fails, Could you help? what's if it possible training by CPU?

Thanks!

My environment is python 3.7.2.
virtualenv -p python3 $HOME/tmp/NeuralVoicePuppetry-venv
(NeuralVoicePuppetry-venv) ➜  ~ python --version
Python 3.7.2

**Comment by dDoom** [comment]
`pip install renderer` correct new name

**Comment by shichaog** [comment]
@dDoom Yes, it works, Thank you!

**Comment by RainEggplant** [comment]
> 
> 
> `pip install renderer` correct new name

It seems that the `renderer` installed by this is not what the project requires. Instead, you'll need to clone [Soft Rasterizer (SoftRas)](https://github.com/ShichenLiu/SoftRas) and install it manually. Also note that you'll need to adapt the source code for pytorch>=1.5 (refer to this issue: [Fix pytorch1.5 compile error](https://github.com/ShichenLiu/SoftRas/issues/56)).
