### ISSUE TITLE
Get training sequence by BaselFaceModel.tgz?

### ISSUE THREAD

**Issue by shichaog** [JustusThies/NeuralVoicePuppetry#11]
Hi @JustusThies, thanks for this great project.
I found example of Sequence_001 for training. Could you help explain how to get following files from raw videos?
```
expression.txt identities.txt intrinsics.txt markers.txt    recording.id   recording.trck rigid.txt
```
Are they matlab codes of  BaselFaceModel.tgz?

Thanks!

**Comment by JustusThies** [comment]
Hey,

these files should contain the tracking information of the sequence.
- 'expression.txt' contains the per frame estimated blendshape coefficients (recording.trck other format (not used))
- 'identities.txt' contains the PCA coefficients (recording.id the same/other format (not used))
- 'intrinsics.txt' the estimated camera intrinsics
- 'markers.txt' contains facial landmarks (not used)
- 'rigid.txt' contains the rigid head poses

To get these parameters you need to have a face tracker. I used my optimization-based facetracker presented in [Face2Face](https://justusthies.github.io/posts/face2face/).
You could try the regression based approach of Guo et al. [3DDFA](https://github.com/cleardusk/3DDFA_V2), or any other face tracker.

Best,
Justus
