### ISSUE TITLE
How to run if my expressions coefficients are in an np array rather that txt format.

### ISSUE THREAD

**Issue by meherabhi** [JustusThies/NeuralVoicePuppetry#15]
Could you elaborate a bit on how to use the data loader?

**Comment by meherabhi** [comment]
size mismatch for mapping: copying a param with shape torch.Size([1, 116, 76, 32]) from checkpoint, the shape in current model is torch.Size([1, 116, 46, 32]).
I am getting the above error when i fix the N_EXPRESSIONS to 46.
where am i going wrong?

**Comment by JustusThies** [comment]
Hey,

the trained model also contains the mappings of all people in the training set, hence, you can not change the N_EXPRESSIONS parameter there.

You want to adapt the inference code where the mapping matrix is computed that maps the internal 'audio expressions' to the expressions of your face model with 46 parameters.
Given the mapping, you can then transform new 'audio expressions' (inferred by the audio2expressionnet) to the blendshape space of your model.

Best,
Justus
