### ISSUE TITLE
About testing with custom data

### ISSUE THREAD

**Issue by MertCokelek** [JustusThies/NeuralVoicePuppetry#17]
Hello dear Mr. Justus Thies, me and my team are having problems with creating output images from the expressions (in default case "expressions.txt" which has 76 expressions). 

We have downloaded FLAME face tracker and the Basel Model, however, we could not understand which function to give this file as parameter. How can we connect the Audio2ExpressionNet and the NeuralRenderer, can you explain in detail? Also, can you give more details on "NeuralRenderingNetwork/models" folder? We could not find a way to use it. 
Thanks in advance.

**Comment by JustusThies** [comment]
Hey,

you can use the inference code and adapt the dimensions to your used model.
I.e., in the inference code a mapping matrix is computed that maps the internal 'audio expressions' to the expressions of your face model. There you need to adapt the dimensions.
Given the mapping, you can transform new 'audio expressions' (inferred by the audio2expressionnet) to the blendshape space of your model.

With these blendshape coefficents you can render uv maps of the face and then use the neural renderer defined in the NeuralRenderingNetwork folder.
The model in this folder can be used in the Pix2Pix/CycleGAN framework as written in the readme.

Best,
Justus
