### ISSUE TITLE
Mapping number of expressions generated from another face model

### ISSUE THREAD

**Issue by genesis02** [JustusThies/NeuralVoicePuppetry#18]
Getting error while running the inference
size mismatch for mapping: copying a param with shape torch.Size([1, 116, 76, 32]) from checkpoint, the shape in current model is torch.Size([1, 116, 64, 32]).
My face model is providing 64 expression coefficients.
Is it  still possible to run the inference using checkpoint latest_netG.pth because for mapping parameter required grad was set  true.
Can you please explain how to modify the inference code to compute mapping matrix that maps the internal 'audio expressions' to the expressions of my face model with 64 parameters.

**Comment by JustusThies** [comment]
Hey,

you can use the inference code and adapt the dimensions to your used model. For model loading you still need to specify the 76. But in the inference code a mapping matrix is computed that maps the internal 'audio expressions' to the expressions of your face model. There you need to adapt the dimensions.
Given the mapping, you can transform new 'audio expressions' (inferred by the audio2expressionnet) to the blendshape space of your model.

Best,
Justus
