### ISSUE TITLE
Number of expressions other than 76

### ISSUE THREAD

**Issue by genesis02** [JustusThies/NeuralVoicePuppetry#19]
Can we used the inference code with face model generating number of expressions other than 76.  If yes please , suggest the changes to be made to the code. Can you suggest face model to use to have 76 expressions.

**Comment by JustusThies** [comment]
Hey,

you can use the inference code and adapt the dimensions to your used model.
I.e., in the inference code a mapping matrix is computed that maps the internal 'audio expressions' to the expressions of your face model. There you need to adapt the dimensions.
Given the mapping, you can transform new 'audio expressions' (inferred by the audio2expressionnet) to the blendshape space of your model.

Best,
Justus
