### ISSUE TITLE
Audio2Expression Training

### ISSUE THREAD

**Issue by JakubReha** [JustusThies/NeuralVoicePuppetry#26]
Hi, what exactly are the identities.txt, intrinsics.txt, markers.txt, recording.id, recording.trck and rigid.txt files and how can I obtain them? Is it supposed to come from the face tracker?

**Comment by JustusThies** [comment]
Hi,
yes, these files are supposed to come from the face tracker.
See https://github.com/JustusThies/NeuralVoicePuppetry/issues/11
Best,
Justus
