### ISSUE TITLE
Visualization of expression.txt using Basel Face Model  

### ISSUE THREAD

**Issue by Macoron** [JustusThies/NeuralVoicePuppetry#3]
Good day,

Thank you for sharing your project! I was trying to visualize expression.txt of Trump inside dateset folder and met some problems.

1. There is no original audio files of Trump or Greta, only encoded audio-features. It will be great if you can share original audio clips too.

2. The link in readme.md directs to very old Basel Face Model 2009. If I understand right this model doesn't have expressions blendshapes. Though 2017 and 2019 have. Is it just wrong link or I'm missing something?

3. The 2019 Basel Face Model has 100 blendshapes for expressions. Your pretrained model has only 76. Why? What blendshapes have been chosen? In which order?

4. I tried to visualize Trump expression.txt using [basel face model viewer](https://github.com/unibas-gravis/basel-face-model-viewer). I put first 76 blendshapes values and rendered each frame. Result is really weird, face model is barely moving. Maybe there are some problems with normalization? 

I attached gif to show my current results:
![1](https://user-images.githubusercontent.com/6161335/86233620-5d22a580-bb9e-11ea-8a8b-258b33fbfabb.gif)

**Comment by JustusThies** [comment]
Hey,

the face model that I'm using is based on the old Basel Face Model with custom expressions (76 expressions, see paper).
The expressions file is containing coefficients for that model and you can not directly apply it to another model.
The file is an example of which format your visual tracking result should have.
If you have a running face tracker and your favourite face model, you create a file that contains the per frame expressions.
In addition you use the Voca DeepSpeech feature extraction to get the audio-features.
With this data, you use the inference code which computes a mapping from the internal 'audio expressions' to the expressions of the used face model (adaption procedure to learn person specific expressions).
This mapping allows you to then generate new facial expressions only based on audio, especially, from a different person (which is basically the test case).

Best,
Justus Thies
