### ISSUE TITLE
The files named './BaselModel/average.obj' and './BaselModel/ExpressionBasis.matrix' are missing

### ISSUE THREAD

**Issue by cenalzw** [JustusThies/NeuralVoicePuppetry#6]
Hey @JustusThies 
Thank you for your impressive work. 

I tried to run the training script of Audio2ExpressionNet. However, when I got into the part of  class 'MorphableModel', I found that 
the files named 'average.obj' and 'ExpressionBasis.matrix' are missing and I still cannot find it after searching. Could you help me with this? I will really appreciate that. Hope to get your reply.

**Comment by JustusThies** [comment]
Hi,
these files contain the morphable face model, i.e., the average face and the expression delta-blendshapes.
You can for example use the Basel face model or the Flame head model (you need to adapt the loading procedure accordingly).
In the original implementation, I use a modified Basel face model (see Paper) which I am not allowed to share.
Best,
Justus Thies

**Comment by zaverichintan** [comment]
Hello @JustusThies,
Could you please share the code to generate the 'average.obj' and 'ExpressionBasis.matrix' files from BFM data? (I have a copy of BFM2019).
Thanks in advance.
