### ISSUE TITLE
Confusion about neual rendering

### ISSUE THREAD

**Issue by cenalzw** [JustusThies/NeuralVoicePuppetry#7]
Hey @JustusThies . Thanks for your excellent work and sharing this code. After I read all of your code carefully, I am confused about 
some parts of your code. 

In the code of 'texture_decoder', I see you input both the rendered neural texture and the background into the texture decoder network. If I understand right, the function of texture decoder  is to interpret the neural texture into RGB image, as shown in Fig.13 of your paper. As the output image does not contain background, I just do not know why we should input a background image into  the texture decoder.  Could you help me with my confusion? Thanks a lot.

**Comment by JustusThies** [comment]
Hi, you are right. For the texture_decoder you don't need to input the background, you can remove that and add a corresponding new U-Net module.
Best
