### ISSUE TITLE
image and audio sync up

### ISSUE THREAD

**Issue by wayneszq** [JustusThies/NeuralVoicePuppetry#8]
Hi, 

Thanks for sharing. 

I'm studying your work, but find it hard to sync up the audio and video feature.  Please help.

I found the video is 25 fps, means 25 frames(images) per second. The audio feature takes a window size of 20ms, which is 50 audio features per second. it's 25 VS 50, image VS auido.

Any suggestion what's the right way to sync this up? one image matches 2 audio feature? OR any other solution?

Thanks again.

**Comment by cenalzw** [comment]
I am facing the same issue, have you fixed it?

**Comment by wayneszq** [comment]
> I am facing the same issue, do you have any idea to solve this?

Still working on it, no good result yet.

**Comment by JustusThies** [comment]
Hi,

the resampling is done in the AudioHandler (https://github.com/TimoBolkart/voca/blob/9e2a759eed0a0e6a75ee0c22d2e09b819f3b420b/utils/audio_handler.py#L125).
The hardcoded sampling rate here is 60. You need to change that to your target fps.

I have introduced a parameter 'target_fps' for that:
# Resample network output from 50 fps to target_fps fps
audio_len_s = float(audio_sample.shape[0]) / sample_rate
num_frames = int(round(audio_len_s * target_fps))
network_output = interpolate_features(network_output[:, 0], 50, target_fps,  output_len=num_frames)


Best,
Justus Thies

**Comment by wayneszq** [comment]
Many thanks.  It works well for me.
